### ISSUE TITLE
Bounties & Hotkey tabs

### ISSUE THREAD

**Issue by Modcat** [Modcat/BlankCanvas#4]
1. Create bounty wall and hotkey tabs both showing different views
2. Create hotkeys with simple design and description so people know which keys to press and what to do

**Comment by AlexanderVladimirov9090** [comment]
Idea:
The hotkeys could be made like this:
Simple:
Icon that correspond on action that is going to be taken after execution.
Next to it combination of keys.

Dynamic:
All hotkeys should change based on what is used at the moment.

When you are in editor hotkeys of editor will popup somewhere.
We have to see where is it good spot to be placed.

When you are in presentation module, the hotkeys are switched to presentation hotkeys.

What you think?
And Could you Refresh me on what is bounty wall?
